export const gunlukProgram = [
    {
        id: "uyandiginda",
        sira: 1,
        saat: "10:00",
        baslik: "Uyanınca",
        kisaBaslik: "Kefir",
        emoji: "🥛",
        tur: "ogun",
        bildirimBasligi: "Günaydın güzelim 🌸",
        bildirimMesaji:
            "Kefir saatin geldi. Güne kendine iyi bakarak başlayalım ❤️",
        icerikler: [
            "1 su bardağı laktozsuz kefir",
            "1 tatlı kaşığı chia tohumu",
            "1 tatlı kaşığı keten tohumu",
            "2 adet peynirli karabuğday patlağı",
        ],
        notlar: [],
    },
    {
        id: "sabah",
        sira: 2,
        saat: "12:00",
        baslik: "Sabah",
        kisaBaslik: "Kahvaltı",
        emoji: "🍳",
        tur: "ogun",
        bildirimBasligi: "Kahvaltı zamanı 🍳",
        bildirimMesaji:
            "Güzel bir kahvaltıyla enerjini yenileme zamanı ❤️",
        icerikler: [
            "1 adet yumurta",
            "1 porsiyon bol yeşillikli salata",
            "5 adet zeytin",
            "1 adet glutensiz ekmek",
            "1 porsiyon süzme peynir",
        ],
        notlar: [
            "Tenis günlerinde 2 adet yumurta",
            "Salataya 1 yemek kaşığı zeytinyağı eklenebilir",
            "5 zeytin yerine 2 tam ceviz veya 1/4 avokado",
            "Glutensiz ekmek yerine karabuğday veya karakılçık ekmek, 2 karabuğday patlağı ya da 2 glutensiz wasa",
            "Süzme peynir yerine 2 yemek kaşığı lor peyniri",
        ],
    },
    {
        id: "ara-ogun-1",
        sira: 3,
        saat: "14:00",
        baslik: "Ara Öğün I",
        kisaBaslik: "Bitki Çayı",
        emoji: "🍵",
        tur: "ara-ogun",
        bildirimBasligi: "Küçük bir mola 🍵",
        bildirimMesaji:
            "Bitki çayını hazırlama zamanı güzelim. Bugün de çok iyi gidiyorsun ❤️",
        icerikler: [
            "1 fincan bitki çayı",
        ],
        notlar: [
            "Lazika prebiyotikli veya kolajenli yeşil çay",
        ],
    },
    {
        id: "ogle",
        sira: 4,
        saat: "15:00",
        baslik: "Öğle",
        kisaBaslik: "Öğle Öğünü",
        emoji: "🍎",
        tur: "ogun",
        bildirimBasligi: "Öğle öğünün hazır 🍎",
        bildirimMesaji:
            "Öğle öğününü atlamıyoruz. Kendine iyi baktığın için seninle gurur duyuyorum ❤️",
        icerikler: [
            "Programdaki seçeneklerden bir öğle öğünü seç",
        ],
        secenekler: [
            "4 yemek kaşığı yoğurt ve 1 adet elma",
            "4 yemek kaşığı yoğurt ve 1 adet armut",
            "4 yemek kaşığı yoğurt ve 1/2 su bardağı kırmızı meyve",
            "4 yemek kaşığı yoğurt ve 5 adet çilek",
            "4 yemek kaşığı yoğurt ve 1 adet şeftali",
            "4 yemek kaşığı yoğurt ve 3 adet kayısı",
            "Meyve seçeneğine 1 tatlı kaşığı tahin veya şekersiz fıstık ezmesi ve 2 yemek kaşığı şekersiz granola",
            "Bitkisel sütlü latte ve 2 adet hurma",
            "Bitkisel sütlü latte ve 2 adet gün kurusu",
            "10 adet çiğ badem",
            "2 tam ceviz",
            "8 adet çiğ fındık",
            "1 tatlı kaşığı tahin",
            "1 tatlı kaşığı şekersiz fıstık ezmesi",
            "2 su bardağı ayran ve 4 adet karabuğdaylı Altınbaşak galeta",
        ],
        notlar: [
            "Tenis günlerinde proteinli yoğurt kullanılabilir",
        ],
    },
    {
        id: "ara-ogun-2",
        sira: 5,
        saat: "16:00",
        baslik: "Ara Öğün II",
        kisaBaslik: "Bitki Çayı",
        emoji: "🍵",
        tur: "ara-ogun",
        bildirimBasligi: "Bitki çayı zamanı 🌿",
        bildirimMesaji:
            "Kısa bir mola verip çayını içme zamanı güzelim ❤️",
        icerikler: [
            "1 fincan bitki çayı",
        ],
        notlar: [
            "Lazika kolajenli yeşil çay",
        ],
    },
    {
        id: "aksam",
        sira: 6,
        saat: "18:30",
        baslik: "Akşam",
        kisaBaslik: "Akşam Yemeği",
        emoji: "🥗",
        tur: "ogun",
        bildirimBasligi: "Akşam yemeği zamanı 🥗",
        bildirimMesaji:
            "Günün dengeli akşam öğününü hazırlama zamanı. Çok güzel ilerliyorsun ❤️",
        icerikler: [
            "1 porsiyon ana yemek",
            "1 porsiyon bol yeşillikli salata",
            "1 adet glutensiz ekmek veya eşdeğeri",
            "3 yemek kaşığı yoğurt",
        ],
        secenekler: [
            "3 adet fırın köfte",
            "5 yemek kaşığı sebzeli et sote",
            "5 yemek kaşığı sebzeli tavuk sote",
            "2 adet derisiz tavuk but",
            "5 yemek kaşığı sebzeli hindi sote",
            "120 gram yağı süzdürülmüş ton balığı",
            "6 yemek kaşığı zeytinyağlı sebze yemeği",
            "6 yemek kaşığı fırın sebze",
            "5 yemek kaşığı bakliyat yemeği",
            "Izgara balık",
            "2 adet kıymalı biber dolması",
            "1 adet karnıyarık",
        ],
        notlar: [
            "Sebze yemeklerinde havuç ve patates olmasın",
            "Salata yağsız tüketilecek",
            "Glutensiz ekmek yerine 3 yemek kaşığı basmati pirinç, 4 yemek kaşığı kinoa, 4 yemek kaşığı karabuğday, 3 yemek kaşığı bulgur pilavı veya 1 büyük kepçe çorba",
            "Yoğurt kaymaksız olmalı; içine çay kaşığı ucuyla toz zencefil ve zerdeçal eklenebilir",
        ],
    },
    {
        id: "yatmadan-once",
        sira: 7,
        saat: "21:00",
        baslik: "Yatmadan Önce",
        kisaBaslik: "Gece Öğünü",
        emoji: "🌙",
        tur: "ogun",
        bildirimBasligi: "Günün son hatırlatması 🌙",
        bildirimMesaji:
            "Bugünün son küçük öğünü geldi. Bugün gösterdiğin çabayla gurur duyuyorum ❤️",
        icerikler: [
            "1 yemek kaşığı çiğ kabak çekirdeği",
            "1 su bardağı ayran",
        ],
        notlar: [
            "Kabak çekirdeği bir gün arayla tüketilecek",
        ],
    },
];

export const suHedefi = 8;
